hostname S1
!
boot-start-marker
boot-end-marker
!
!
!
no aaa new-model
!
!
!
!
!
!
!
!
ip cef
no ipv6 cef
!
!
!
spanning-tree mode pvst
spanning-tree extend system-id
!
!
! 
!
!
!
!
!
!
!
!
!
!
!
!
interface Loopback0
 ip address 6.6.6.6 255.255.255.255
!
interface Port-channel1
 switchport trunk encapsulation dot1q
!
interface GigabitEthernet0/0
 no switchport
 ip address 192.168.46.6 255.255.255.0
 negotiation auto
!
interface GigabitEthernet0/1
 switchport trunk encapsulation dot1q
 negotiation auto
 channel-group 1 mode active
!
interface GigabitEthernet0/2
 switchport trunk encapsulation dot1q
 negotiation auto
 channel-group 1 mode active
!
interface GigabitEthernet0/3
 negotiation auto
!
interface GigabitEthernet1/1
 negotiation auto
!
interface GigabitEthernet1/2
 negotiation auto
!
interface GigabitEthernet1/3
 negotiation auto
!
interface GigabitEthernet2/1
 negotiation auto
!
interface GigabitEthernet2/2
 negotiation auto
!
interface GigabitEthernet2/3
 negotiation auto
!
interface GigabitEthernet3/0
 negotiation auto
!
interface GigabitEthernet3/1
 negotiation auto
!
interface GigabitEthernet3/2
 negotiation auto
!
interface GigabitEthernet3/3
 negotiation auto
!
!
router eigrp 1
 network 192.168.46.0
!
ip forward-protocol nd
!
ip http server
ip http secure-server

line con 0
 logging synchronous
line aux 0
line vty 0 4
!
!
end