hostname R9
!
boot-start-marker
boot-end-marker
!
logging message-counter syslog
!
no aaa new-model
ip source-route
no ip icmp rate-limit unreachable
ip cef
!
!
!
!
no ip domain lookup
no ipv6 cef
!
multilink bundle-name authenticated
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
!
archive
 log config
  hidekeys
! 
!
!
!
!
ip tcp synwait-time 5
!
!
!
!
interface Loopback0
 ip address 9.9.9.9 255.255.255.255
!
interface Tunnel0
 ip address 192.168.79.9 255.255.255.0
 tunnel source 192.168.89.9
 tunnel destination 192.168.78.7
!
interface Ethernet0/0
 no ip address
 shutdown
 duplex auto
!
interface GigabitEthernet0/0
 ip address 192.168.89.9 255.255.255.0
 duplex full
 speed 1000
 media-type gbic
 negotiation auto
!
interface GigabitEthernet1/0
 ip address 192.168.91.9 255.255.255.0
 negotiation auto
!
interface GigabitEthernet2/0
 no ip address
 shutdown
 negotiation auto
!
interface GigabitEthernet3/0
 no ip address
 shutdown
 negotiation auto
!
router bgp 5
 no synchronization
 bgp log-neighbor-changes
 network 9.9.9.9 mask 255.255.255.255
 neighbor 192.168.79.7 remote-as 4
 neighbor 192.168.79.7 ebgp-multihop 2
 no auto-summary
!
ip forward-protocol nd
ip route 10.10.10.10 255.255.255.255 192.168.91.10
ip route 192.168.78.7 255.255.255.255 192.168.89.8
no ip http server
no ip http secure-server
!
!
!
no cdp log mismatch duplex
!
!
!
!
!
!
control-plane
!
!
!
!
!
!
!
gatekeeper
 shutdown
!
!
line con 0
 exec-timeout 0 0
 privilege level 15
 logging synchronous
 stopbits 1
line aux 0
 exec-timeout 0 0
 privilege level 15
 logging synchronous
 stopbits 1
line vty 0 4
 login
!
end
